const React = require("react");
const { renderToStaticMarkup } = require("react-dom/server");
const fs = require("fs");
const SettingsManager = require("../src/components/admin/SettingsManager").default;
const OrderBuilder = require("../src/components/pos/OrderBuilder").default;
const css = fs.readFileSync("/tmp/tw.css", "utf8");
const settings = { _id: "s1", rupeesPerPoint: 100, printerType: "EPSON", paperWidth: 48, autoCut: true, autoFillDeliveryAddress: true, storeName: "Sevesto Cafe", storePhone: "0300-1234567", storeAddress: "Example Street", speedDial: {} };
const sm = renderToStaticMarkup(React.createElement(SettingsManager, { initialSettings: settings, initialProducts: [{ _id: "p1", name: "Sample Product" }] }));
console.log("RENDER_PIN_SECTION:", sm.includes("Change PIN") && sm.includes("Security") ? "PRESENT" : "MISSING");
console.log("RENDER_BACKUP_SECTION:", sm.includes("Backup &amp; Restore") ? "PRESENT" : "MISSING");
console.log("RENDER_STORE_BRANDING:", sm.includes("Store Branding") ? "PRESENT" : "MISSING");
fs.writeFileSync("/tmp/settings-render.html", `<!doctype html><html><head><meta charset="utf-8"><title>Sevesto POS — Settings (rendered)</title><style>${css}</style></head><body style="background:#faf9f7;padding:24px">${sm}</body></html>`);
const ob = renderToStaticMarkup(React.createElement(OrderBuilder, { orderType: "dine_in", products: [], waiters: [{ _id: "w1", name: "Ahmed (Waiter)" }], categories: [] }));
const asides = (ob.match(/<aside/g) || []).length;
console.log("RENDER_ORDER_FLOW_ASIDES:", asides, "(expected 1)");
console.log("RENDER_WAITER_SELECT:", ob.includes("Set Waiter") ? "PRESENT" : "MISSING");
console.log("RENDER_GUEST_HINT:", ob.includes("Guests must be at least 1") ? "PRESENT" : "MISSING");
console.log("RENDER_PROOFS_OK");
